<a href="https://colab.research.google.com/github/raiadi96/Pytorch/blob/master/Linear_Regression_using_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch.nn as nn #contains utility classes for building neural networks
import torch
import numpy as np

In [0]:
#we create dummy inputs and their dummy targets and then convert them into to a tensor

inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')


targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


In [17]:
#in order to feed data to the neural network we first need to convert the data into a tensor dataset
from torch.utils.data import TensorDataset
train_ds = TensorDataset(inputs,targets)
train_ds[0:5]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.],
         [102.,  43.,  37.],
         [ 69.,  96.,  70.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

In [0]:
#it is important to split data into batches before being sent for training. this can be done using DataLoader. DataLoader also has utility for shuffling data
from torch.utils.data import DataLoader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle = True)

In [19]:
#we use nn.linear for creating the model. nn.linear will take 2 parameters in-shape and out-shape, inshape is the number of parameters that will be fed into the system and outshape is the shape of the output

model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.3947,  0.0448, -0.0688],
        [ 0.4832, -0.2889, -0.2036]], requires_grad=True)
Parameter containing:
tensor([0.1569, 0.1604], requires_grad=True)


In [0]:
#loss function
#we use mean square error function in order to compute the loss

import torch.nn.functional as F

#mse formula = 1/n*(ypred - ytarg)^2

loss_fn = F.mse_loss

#optimiser function
#in order to optimise our results we use stochastic gradient descent. this allows for adjust the weights in a more optimised and effecient manner
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [0]:
#steps in training a model
#for each epoch
# 1. Generate Predictions
# 2. Calculate the loss that occurs 
# 3. Compute the optimization metrics.
# 4. Adjust the weights
# 5. Reset the weights to zero

def fit(num_epochs, model, loss_fn, opt):
  for epoch in range(num_epochs):
    for xb,yb in train_dl:
      pred = model(xb)
      loss = loss_fn(pred,yb)
      loss.backward()
      opt.step()
      opt.zero_grad()

    if (epoch+1)%10==0:
      print("Epoch [{}/{}], Loss: {:.4f}".format(epoch+1, num_epochs, loss.item()))

In [29]:
fit(2000, model, loss_fn, opt)

Epoch [10/2000], Loss: 0.6852
Epoch [20/2000], Loss: 0.4698
Epoch [30/2000], Loss: 0.5576
Epoch [40/2000], Loss: 0.7282
Epoch [50/2000], Loss: 0.6716
Epoch [60/2000], Loss: 0.6038
Epoch [70/2000], Loss: 0.7293
Epoch [80/2000], Loss: 0.8270
Epoch [90/2000], Loss: 0.8583
Epoch [100/2000], Loss: 0.6019
Epoch [110/2000], Loss: 0.5406
Epoch [120/2000], Loss: 0.5924
Epoch [130/2000], Loss: 0.8145
Epoch [140/2000], Loss: 0.4567
Epoch [150/2000], Loss: 0.5809
Epoch [160/2000], Loss: 0.5658
Epoch [170/2000], Loss: 0.7154
Epoch [180/2000], Loss: 0.5956
Epoch [190/2000], Loss: 0.5576
Epoch [200/2000], Loss: 0.3406
Epoch [210/2000], Loss: 0.6755
Epoch [220/2000], Loss: 0.6474
Epoch [230/2000], Loss: 0.3364
Epoch [240/2000], Loss: 0.4879
Epoch [250/2000], Loss: 0.3473
Epoch [260/2000], Loss: 0.5199
Epoch [270/2000], Loss: 0.4843
Epoch [280/2000], Loss: 0.4013
Epoch [290/2000], Loss: 0.3605
Epoch [300/2000], Loss: 0.6465
Epoch [310/2000], Loss: 0.5689
Epoch [320/2000], Loss: 0.8362
Epoch [330/2000],

In [0]:
#final predictions after 1000 epochs


In [30]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 57.2001,  70.3394],
        [ 82.2024, 100.6572],
        [118.7064, 132.9607],
        [ 21.0857,  37.0167],
        [101.9362, 119.1443],
        [ 57.2001,  70.3394],
        [ 82.2024, 100.6572],
        [118.7064, 132.9607],
        [ 21.0857,  37.0167],
        [101.9362, 119.1443],
        [ 57.2001,  70.3394],
        [ 82.2024, 100.6572],
        [118.7064, 132.9607],
        [ 21.0857,  37.0167],
        [101.9362, 119.1443]], grad_fn=<AddmmBackward>)

In [31]:
#actual targets were
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])